# Generated by Django 5.2.1 on 2025-05-28 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'category',
                    models.PositiveIntegerField(choices=[(0, '휘낭시에'), (1, '조각케이크'), (2, '스콘'), (3, '오늘의 메뉴')])
                ),
                ('name', models.CharField(max_length=30)),
                ('price', models.PositiveIntegerField()),
                ('cmt', models.CharField(blank=True, max_length=100)),
                ('img', models.ImageField(upload_to='cookies')),
            ],
            options={
                'verbose_name_plural': '구움과자 상품',
                'db_table': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_sale', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': '판매 상태',
                'db_table': 'Sale',
            },
        ),
        migrations.CreateModel(
            name='Cookies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'status',
                    models.PositiveIntegerField(choices=[(0, '판매 대기중'), (1, '판매중'), (2, '재고 소진'), (3, '시즌 종료')])
                ),
                ('total', models.PositiveIntegerField()),
                ('safe', models.PositiveIntegerField()),
                ('current', models.PositiveIntegerField()),
                ('index', models.PositiveIntegerField(unique=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='products.products')),
            ],
            options={
                'verbose_name_plural': '구움과자',
                'db_table': 'Cookies',
            },
        ),
    ]
