# Generated by Django 5.2.1 on 2025-05-28 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Times',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start', models.PositiveIntegerField()),
                ('end', models.PositiveIntegerField()),
                ('interval', models.IntegerField(choices=[(20, '20분'), (30, '30분')])),
                ('selected', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': '구움과자 픽업시간',
                'db_table': 'Times',
            },
        ),
        migrations.CreateModel(
            name='Pickups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str_time', models.CharField(max_length=5)),
                ('reserved', models.BooleanField(default=False)),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.times')),
            ],
            options={
                'verbose_name_plural': '구움과자 픽업 테이블',
                'db_table': 'Pickups',
            },
        ),
    ]
