# Generated by Django 5.2.1 on 2025-06-01 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_times_pickups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='cmt',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
