# Generated by Django 5.2.1 on 2025-06-03 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_products_cmt_alter_products_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sale',
            new_name='Sales',
        ),
        migrations.AlterModelTable(
            name='sales',
            table='Sales',
        ),
    ]
