# Generated by Django 5.2.1 on 2025-06-11 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_sale_sales_alter_sales_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='BitDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('days', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name_plural': '테스트용 스케줄',
                'db_table': 'BitDays',
            },
        ),
        migrations.AlterModelOptions(
            name='cookies',
            options={'verbose_name_plural': '구움과자 판매'},
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.PositiveIntegerField(choices=[(1, '휘낭시에'), (2, '조각케이크'), (3, '스콘'), (4, '오늘의 메뉴')]),
        ),
    ]
