# Generated by Django 5.2.1 on 2025-06-11 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_bitdays_alter_cookies_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cakes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('cmt', models.CharField(blank=True, max_length=1000)),
                ('img', models.ImageField(upload_to='cakes')),
                ('display', models.PositiveIntegerField(choices=[(0, '상품 숨김'), (1, '상품 노출'), (2, '상품 노출 [예약 마감]'), (3, '상품 노출 [시즌 종료]')])),
            ],
            options={
                'verbose_name_plural': '홀케이크 판매',
                'db_table': 'Cakes',
            },
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveIntegerField(choices=[(1, '호수'), (2, '과일 추가'), (3, '과일 믹스'), (4, '생크림 변경'), (5, '시트 변경'), (6, '초코 글라사쥬')])),
                ('name', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name_plural': '홀케이크 옵션',
                'db_table': 'Options',
            },
        ),
        migrations.CreateModel(
            name='Schedules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('days', models.PositiveIntegerField()),
                ('start_time', models.PositiveIntegerField()),
                ('end_time', models.PositiveIntegerField()),
                ('interval', models.IntegerField(choices=[(20, '20분'), (30, '30분')])),
            ],
            options={
                'verbose_name_plural': '홀케이크 스케줄',
                'db_table': 'Schedules',
            },
        ),
        migrations.CreateModel(
            name='CakeOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.cakes')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.options')),
            ],
            options={
                'db_table': 'CakeOptions',
            },
        ),
        migrations.AddField(
            model_name='cakes',
            name='options',
            field=models.ManyToManyField(through='products.CakeOptions', to='products.options'),
        ),
        migrations.CreateModel(
            name='CakeSchedules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.cakes')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.schedules')),
            ],
            options={
                'db_table': 'CakeSchedules',
            },
        ),
        migrations.AddField(
            model_name='cakes',
            name='schedules',
            field=models.ManyToManyField(through='products.CakeSchedules', to='products.schedules'),
        ),
    ]
